-- Create Database 
CREATE DATABASE online_clothing_management_system;

-- Create Products table
CREATE TABLE Products (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Brand VARCHAR(255) NOT NULL,
    Category VARCHAR(255) NOT NULL,
    Category_id VARCHAR(255) NOT NULL,
    Price INT NOT NULL,
    Colors JSON NOT NULL,
    Size JSON NOT NULL,
    InStock BOOLEAN NOT NULL,
    Quantity INT NOT NULL,
    Discount INT DEFAULT 0,
    ImageUrl VARCHAR(255) NOT NULL
);

 -- Add a new column named "Gender" to the existing table
ALTER TABLE Products ADD COLUMN Gender VARCHAR(255) NOT NULL DEFAULT 'Male';

ALTER TABLE Products ADD COLUMN Description VARCHAR(1000) NOT NULL DEFAULT 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Expedita, assumenda? Id consequatur totam necessitatibus animi eius iusto quia laboriosam eum laudantium hic! Rem, commodi praesentium harum officia porro autem incidunt ad aspernatur laboriosam at fugit debitis ipsa, recusandae veniam voluptatem, quaerat necessitatibus placeat eligendi! Fugit, natus rerum, molestias neque officiis, quam vitae eum quod sint eius in. Accusantium neque explicabo corrupti maiores iure culpa repudiandae rerum!';

ALTER TABLE Products ADD COLUMN IsDeleted BOOLEAN NOT NULL DEFAULT false;

-- Saree
INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Saree-1', 'A', 'Saree', 'saree', 2550, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 5, 'assets/Women/Saree/saree_1.jpeg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Saree-2', 'B', 'Saree', 'saree', 3250, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 0, 'assets/Women/Saree/saree_2.jpeg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Saree-3', 'C', 'Saree', 'saree', 4000, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 5, 'assets/Women/Saree/saree_3.jpeg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Saree-4', 'D', 'Saree', 'saree', 2500, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 0, 'assets/Women/Saree/saree_4.jpg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Saree-5', 'E', 'Saree', 'saree', 3000, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 10, 'assets/Women/Saree/saree_5.jpg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Saree-6', 'E', 'Saree', 'saree', 2500, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 20, 'assets/Women/Saree/saree_6.jpeg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

-- Borkha
INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Borkha-1', 'A', 'Borkha', 'borkha', 2000, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 20, 'assets/Women/Borkha/borkha_1.jpeg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Borkha-2', 'B', 'Borkha', 'borkha', 1500, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 0, 'assets/Women/Borkha/borkha_2.jpeg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Borkha-3', 'C', 'Borkha', 'borkha', 1250, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 0, 'assets/Women/Borkha/borkha_3.webp', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Borkha-4', 'D', 'Borkha', 'borkha', 1500, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 10, 'assets/Women/Borkha/borkha_4.jpeg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Borkha-5', 'E', 'Borkha', 'borkha', 2000, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 0, 'assets/Women/Borkha/borkha_5.jpg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Borkha-6', 'A', 'Borkha', 'borkha', 2500, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 0, 'assets/Women/Borkha/borkha_6.jpg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Borkha-7', 'B', 'Borkha', 'borkha', 2650, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 0, 'assets/Women/Borkha/borkha_7.jpg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

-- Men's Sweater
INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Sweater-1', 'A', 'Sweater', 'sweater', 2550, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 5, 'assets/Men/Sweater/sweater_1.jpg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Sweater-2', 'B', 'Sweater', 'sweater', 3250, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 0, 'assets/Men/Sweater/sweater_2.jpg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

-- Women's Sweater
INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Sweater-1', 'A', 'Sweater', 'sweater', 2550, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 5, 'assets/Women/Sweater/sweater_1.jpg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Sweater-2', 'B', 'Sweater', 'sweater', 3250, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 43}, {"Name": "M", "Color": "Black", "Quantity": 17}]', 1, 60, 0, 'assets/Women/Sweater/sweater_2.jpeg', 'Women', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

-- Men's Shirt
INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Shirt-3', 'C', 'Shirt', 'shirt', 2000, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 0, 'assets/Shirt/shirt_3.jpg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Shirt-4', 'D', 'Shirt', 'shirt', 1500, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 10, 'assets/Shirt/shirt_4.webp', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Shirt-5', 'E', 'Shirt', 'shirt', 2500, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 20, 'assets/Shirt/shirt_5.jpg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Shirt-6', 'A', 'Shirt', 'shirt', 1850, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 0, 'assets/Shirt/shirt_6.jpg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Shirt-7', 'B', 'Shirt', 'shirt', 1650, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 10, 'assets/Shirt/shirt_7.jpg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Shirt-8', 'B', 'Shirt', 'shirt', 1650, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 10, 'assets/Shirt/shirt_8.jpeg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

-- Men's Pant
INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Pant-3', 'C', 'Pant', 'pant', 2500, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 10, 'assets/Men/Pant/pant_3.jpg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Pant-4', 'D', 'Pant', 'pant', 2000, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 0, 'assets/Men/Pant/pant_4.jpg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Pant-5', 'E', 'Pant', 'pant', 1700, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 10, 'assets/Men/Pant/pant_5.jpeg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');

INSERT INTO Products (Name, Brand, Category, Category_id, Price, Colors, Size, InStock, Quantity, Discount, ImageUrl, Gender, Description)
VALUES ('Pant-6', 'A', 'Pant', 'pant', 1500, '[]', '[{"Name": "S", "Color": "Black", "Quantity": 12}, {"Name": "M", "Color": "Black", "Quantity": 23}]', 1, 35, 0, 'assets/Men/Pant/pant_6.jpg', 'Men', '    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.     Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta, dolore tempora! Accusamus sint dolorum, dicta assumenda nostrum optio architecto nam perferendis similique tempora at quos atque ullam natus doloremque reiciendis.');
