CREATE TABLE User (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Password VARCHAR(100) NOT NULL,
    IsDeleted BOOLEAN
);
